import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import ReduxProvider from '@/redux/Provider'
import { Toaster } from '@/components/ui/toaster'

const open_sanse = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Store setup app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={open_sanse.className}>{children}
        <Toaster />
        </body>
      </ReduxProvider>
    </html>
  )
}
